### ISSUE TITLE
Use python 3.12, update version to 0.1.4, add authors - 35

### ISSUE THREAD

**Issue by redhat-qe-bot1** [RedHatQE/must-gather-explorer#36]
[Auto generated]
Number: [#35]

**Comment by redhat-qe-bot2** [comment]
[38;5;179mmust-gather-explorer[0m[pull_request][a7e9-11ef-98e8-0cc10063072b][PR 35]: Closing issue for PR: Use python 3.12, update version to 0.1.4, add authors.
PR was closed.
