### ISSUE TITLE
Print specified yaml fields, like .spec.storageClassName - 54

### ISSUE THREAD

**Issue by redhat-qe-bot1** [RedHatQE/must-gather-explorer#55]
[Auto generated]
Number: [#54]

**Comment by redhat-qe-bot2** [comment]
[38;5;223mmust-gather-explorer[0m[pull_request][14964280-b2f8-11ef-9d7b-7f408df3c186][PR 54]: Closing issue for PR: Print specified yaml fields, like .spec.storageClassName.
PR was closed.
