### ISSUE TITLE
Remove must_gather_shell function, call call_actions direct - 60

### ISSUE THREAD

**Issue by redhat-qe-bot2** [RedHatQE/must-gather-explorer#61]
[Auto generated]
Number: [#60]

**Comment by redhat-qe-bot1** [comment]
[38;5;169mmust-gather-explorer[0m[pull_request][538f30d0-b557-11ef-8c6b-51c6cdb6485e][PR 60]: Closing issue for PR: Remove must_gather_shell function, call call_actions direct.
PR was closed.
