### ISSUE TITLE
feat: Update pre-commit config with new hook versions and repositories - 6

### ISSUE THREAD

**Issue by redhat-qe-bot1** [RedHatQE/must-gather-explorer#7]
[Auto generated]
Number: [#6]

**Comment by rh-bot-1** [comment]
[38;5;44mmust-gather-explorer[0m[pull_request][7e48-11ef-80e2-3bcf49a46b22][PR 6]: Closing issue for PR: feat: Update pre-commit config with new hook versions and repositories.
PR was closed.
