### ISSUE TITLE
Get resource by alias, store kinds lowercase - 8

### ISSUE THREAD

**Issue by redhat-qe-bot1** [RedHatQE/must-gather-explorer#9]
[Auto generated]
Number: [#8]

**Comment by redhat-qe-bot2** [comment]
[38;5;65mmust-gather-explorer[0m[pull_request][7fda-11ef-985f-c0e716488cb5][PR 8]: Closing issue for PR: Get resource by alias, store kinds lowercase.
PR was closed.
